/**
 * Sync wiki.warframe.com Lua modules into `data/raw/wiki/`.
 *
 * Fetches each module via `?action=raw` (no MediaWiki parsing, no API
 * authentication, no rate-limiting beyond the wiki's normal HTTP throttle).
 * Prepends a source-URL + license header comment to each file so the
 * provenance and CC-BY-SA attribution travels with the data.
 *
 * The router module `Module:Weapons/data` itself uses Scribunto's
 * `mw.loadData` + metatables and is NOT pure data — we mirror its eight
 * subpages instead, which are pure table literals safe to luaparse (see the
 * MODULES list below for the full set).
 *
 * Network-only. The build never calls this; `read-wiki.ts` parses from disk.
 * Run via `bun run scripts/sync-wiki.ts` or as part of `bun run data:sync`.
 */

import { createHash } from "node:crypto"
import { mkdir, writeFile } from "node:fs/promises"
import { resolve } from "node:path"

import { fetchRetry } from "./build/http"

/** Modules we mirror. `Module:Weapons/data/{primary,secondary,...}` are the
 *  eight subpages declared by the router; the other seven are independent
 *  top-level Module pages. All are pure data per the upstream contract. */
const MODULES = [
  "Weapons/data/primary",
  "Weapons/data/secondary",
  "Weapons/data/melee",
  "Weapons/data/archwing",
  "Weapons/data/companion",
  "Weapons/data/railjack",
  "Weapons/data/modular",
  "Weapons/data/misc",
  "Warframes/data",
  "Companions/data",
  "Arcane/data",
  "Mods/data",
  "Stances/data",
  "Focus/data",
  "Avionics/data",
] as const

const REPO_ROOT = resolve(import.meta.dirname, "..")
const OUT_DIR = resolve(REPO_ROOT, "data/raw/wiki")
const PINS_PATH = resolve(REPO_ROOT, "data/PINS.json")

async function fetchText(url: string): Promise<string> {
  const res = await fetchRetry(url)
  return await res.text()
}

function moduleToFilename(module: string): string {
  return module.replace(/\//g, "_") + ".lua"
}

interface WikiPin {
  module: string
  file: string
  sha256: string
  bytes: number
  fetchedAt: string
}

async function main() {
  console.log(`Mirroring ${MODULES.length} wiki modules to ${OUT_DIR}…`)
  await mkdir(OUT_DIR, { recursive: true })

  const pins: WikiPin[] = []
  for (const m of MODULES) {
    const url = `https://wiki.warframe.com/index.php?title=Module:${m}&action=raw`
    process.stdout.write(`  Module:${m}… `)
    const body = await fetchText(url)
    const header =
      `-- Source: ${url}\n` +
      `-- Mirror license: CC-BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)\n` +
      `-- Mirrored: ${new Date().toISOString()}\n` +
      `-- DO NOT EDIT — regenerated by scripts/sync-wiki.ts\n` +
      `\n`
    const content = header + body
    const file = moduleToFilename(m)
    await writeFile(resolve(OUT_DIR, file), content, "utf8")
    pins.push({
      module: m,
      file,
      sha256: createHash("sha256").update(body).digest("hex"),
      bytes: body.length,
      fetchedAt: new Date().toISOString(),
    })
    process.stdout.write(`${(body.length / 1024).toFixed(1)} KB\n`)
  }

  // Merge wiki pins into the existing PINS.json (sync-de.ts writes the DE
  // half). If PINS.json doesn't exist yet, start with just the wiki half.
  let existing: Record<string, unknown> = {}
  try {
    const txt = await Bun.file(PINS_PATH).text()
    existing = JSON.parse(txt)
  } catch {
    // First run, no PINS.json yet — fine.
  }
  const merged = {
    ...existing,
    wiki: { fetchedAt: new Date().toISOString(), modules: pins },
  }
  await writeFile(PINS_PATH, JSON.stringify(merged, null, 2) + "\n", "utf8")

  console.log(`\n✓ ${MODULES.length} modules → data/raw/wiki/`)
  console.log(`✓ data/PINS.json updated with wiki section`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
